services:
  - type: web
    name: radamconstruction
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    preDeployCommand: "python run_migrations.py"
