services:
  - type: web
    name: radamconstruction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: wsgi.py
