"""add alt_text to service and portfolio_item

Revision ID: 1d56166c6e04
Revises: 9c6ee2f73c18
Create Date: 2026-06-03 01:51:58.494132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d56166c6e04'
down_revision = '9c6ee2f73c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.String(), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('alt_text')

    with op.batch_alter_table('portfolio_items', schema=None) as batch_op:
        batch_op.drop_column('alt_text')

    # ### end Alembic commands ###
