"""fix portfolio image foreign key

Revision ID: bf111ce50766
Revises: 74910ae84611
Create Date: 2025-09-09 13:09:06.411630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf111ce50766'
down_revision = '74910ae84611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
